### ISSUE TITLE
Cannot connect to Strapi, Status code 403

### ISSUE THREAD

**Issue by rjain15** [strapi/strapi-examples#128]
**Node.js version**:
node v12.1.0
**npm version**:
npm 6.9.0
**Strapi version**:
strapi 3.0.0-beta 11
**Operating system**:

mac
**Which example is causing problem?**
https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/#allowaccess

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Graphql Query doesn't work. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**
```
yarn start
..
success copy gatsby files - 0.058 s
success onPreBootstrap - 0.010 s
Authenticate Strapi user
Authenticate Strapi user: 501.412ms
Starting to fetch data from Strapi (articles)
Starting to fetch data from Strapi (users)
(node:33533) Warning: Label 'Fetch Strapi data' already exists for console.time()

 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403



  **Error: Request failed with status code 403**
  
  - createError.js:16 createError
    [karma-client]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [karma-client]/[axios]/lib/core/settle.js:18:12
  
  - http.js:202 IncomingMessage.handleStreamEnd
    [karma-client]/[axios]/lib/adapters/http.js:202:11
  
  - task_queues.js:84 processTicksAndRejections
    internal/process/task_queues.js:84:17
  

warn The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.878 s
success building schema - 0.252 s
success createPages - 0.002 s
success createPagesStatefully - 0.045 s
success onPreExtractQueries - 0.004 s
success update schema - 0.025 s
success extract queries from components - 0.286 s
success write out requires - 0.005 s
```
**What is the expected behavior?**

I can fetch articles from strapi playground
http://localhost:1337/graphql

Doesn't work when I try to get from gatsby
http://localhost:8000/___graphql

There is no method allStrapiArticle. 
I think the connection from client to server is not working. Tried authenticated, unauthenticated all possible options

**Comment by rjain15** [comment]
Tried deleting the .cache directory, didn't work.

**Comment by sorensenjg** [comment]
I just ran into this too

**Comment by msmaromi** [comment]
Make sure articles & users has public permissions

**Comment by lauriejim** [comment]
Hello!

You get this error during the `Users` fetch all request.
`Starting to fetch data from Strapi (users)`

If you continue the article you will have an instruction that indicates you to allow `Users - find`
This action will remove this `403` error.

### Article content
Allow access to User
Remember, when we created the content type we created a relation between User and Articles.

Like Article,User, link is likewise, by default, restricted. But Gatsby needs access, so to allow access, visit the Auth and Permissions section for Public role, click on Public, select the User - find action and save. After saving; Gatsby will have access to all the necessary content types managed by Strapi (for this tutorial).

Restart Strapi from the command line, inside the cms folder - first by Ctrl+ C to stop the server; and then typing strapi develop, to restart it.

**Comment by rmcsharry** [comment]
For anyone else landing here.

If you name your ContentType using underscores, the strapi api exposes them with hypens.

So if you have a content type called `Hero_Block` then that will be exposed as 

`http://localhost:1337/hero-blocks`

Which is what you must use in your gatsby-node.js:

```
    {
      resolve: "gatsby-source-strapi",
      options: {
        apiURL: process.env.API_URL || "http://localhost:1337",
        contentTypes: [
          // List of the Content Types you want to be able to request from Strapi.
          "block",
          "hero-block",
        ],
        queryLimit: 1000,
      },
    }, 
```

**Comment by marieqg** [comment]
Are you sure about the singular ? 
I tried with plural and singular, and it only works when it's in plural ...

**Comment by girafffene** [comment]
Has anyone figured out a solution to this? I've allowed public user to "find" and "findone" on all applicable contentTypes and singleTypes, I have my queryLimit set to 5000, I removed the trailing forward slash from my API Url in the config.js file, I've cleaned the cache folder and yet somehow I still can't get gatsby to fetch my strapi data

**Comment by zmrhaljiri** [comment]
Me too, with proper accesses, query limits, and naming set, still receiving
```
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:
Request failed with status code 404
```
Please can anyone take a look at that issue?

**Comment by jalal246** [comment]
i have the same issue too, and amazingly permissions reset for each build.. so i have each time to update Permissions manually and then build

**Comment by lharrill01** [comment]
You have to go into SETTINGS -> USERS-PERMISSIONS and under USER check find and findone and that should fix the issue.

**Comment by jalal246** [comment]
> You have to go into SETTINGS -> USERS-PERMISSIONS and under USER check find and findone and that should fix the issue.

@lharrill01, in my case Permissions, are being reset. See the issue here: https://github.com/strapi/strapi/issues/8528

**Comment by bast111** [comment]
> and

Still having the same problem with the gatsby-strapi-blog starter and even with the new permissions on User still not working...

**Comment by nobisro** [comment]
For me, this was caused by using a Read-only API token. Using a full-access token fixed the issue.

**Comment by SergioChizhikov** [comment]
Allow access to the Content-Types Builder plugin by checking Select all for both CONTENT-TYPES and COMPONENTS.  In my case, this was missed and was causing a 403 error.
